'use client';
import {useEffect,useState} from 'react';
import {plans,products,services} from '../lib/data';
export default function AdminPanel(){
const [quotes,setQuotes]=useState([]);
useEffect(()=>setQuotes(JSON.parse(localStorage.getItem('legacyjs_quotes')||'[]')),[]);
function status(id,s){const n=quotes.map(q=>q.id===id?{...q,status:s}:q);setQuotes(n);localStorage.setItem('legacyjs_quotes',JSON.stringify(n))}
function clear(){if(confirm('Apagar orçamentos locais?')){localStorage.removeItem('legacyjs_quotes');setQuotes([])}}
return <div className="admin"><div className="stats"><div><span>Pedidos</span><b>{quotes.length}</b></div><div><span>Serviços</span><b>{services.length}</b></div><div><span>Planos</span><b>{plans.length}</b></div><div><span>Produtos</span><b>{products.length}</b></div></div><section className="panel"><div className="title"><div><span>Orçamentos</span><h2>Pedidos recebidos</h2></div><button onClick={clear}>Limpar</button></div>{!quotes.length&&<p className="muted">Nenhum orçamento salvo ainda. Teste criando um em /orcamento.</p>}<div className="quotes">{quotes.map(q=><article key={q.id}><div><span>{q.createdAt}</span><h3>{q.name}</h3><p>{q.contact}</p><p><b>{q.plan}</b> • R$ {Number(q.total).toFixed(2).replace('.',',')}</p><p>{q.desc}</p>{q.addons?.length>0&&<small>Extras: {q.addons.join(', ')}</small>}</div><select value={q.status} onChange={e=>status(q.id,e.target.value)}><option>Pendente</option><option>Em análise</option><option>Aguardando pagamento</option><option>Em desenvolvimento</option><option>Entregue</option><option>Cancelado</option></select></article>)}</div></section><section className="panel"><div className="title"><div><span>Versão principal</span><h2>Recursos incluídos</h2></div></div><div className="features"><p>✅ Site público limpo</p><p>✅ Serviços e planos</p><p>✅ Configurador de orçamento</p><p>✅ Orçamentos no localStorage</p><p>✅ Portfólio</p><p>✅ Produtos prontos</p><p>✅ Cliente visual</p><p>✅ Tickets visual</p></div></section></div>
}
